# Churn Modelling

In [1]:
#import libraries
import pandas as pd
import numpy as np

#np.set_printoptions(threshold=np.inf)
np.set_printoptions(threshold=1000)

In [2]:
df = pd.read_csv('Churn_Modelling.csv')
df.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [3]:
# Checking null Values
df.isnull().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [4]:
x= df.iloc[:,3:-1]
print(type(x))
print(x)

<class 'pandas.core.frame.DataFrame'>
      CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0             619    France  Female   42       2       0.00              1   
1             608     Spain  Female   41       1   83807.86              1   
2             502    France  Female   42       8  159660.80              3   
3             699    France  Female   39       1       0.00              2   
4             850     Spain  Female   43       2  125510.82              1   
...           ...       ...     ...  ...     ...        ...            ...   
9995          771    France    Male   39       5       0.00              2   
9996          516    France    Male   35      10   57369.61              1   
9997          709    France  Female   36       7       0.00              1   
9998          772   Germany    Male   42       3   75075.31              2   
9999          792    France  Female   28       4  130142.79              1   

      HasCrCard  IsActive

In [5]:
y= df.iloc[:,-1]
print(type(y))
print(y)

<class 'pandas.core.series.Series'>
0       1
1       0
2       1
3       0
4       0
       ..
9995    0
9996    0
9997    1
9998    1
9999    0
Name: Exited, Length: 10000, dtype: int64


### Encoding Categorical Data

In [6]:
# import libraries
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder,OrdinalEncoder,LabelEncoder

Geography and Gender are categoriacal values <br>
Geography -> Label Encoder or Ordinal Encoder <br>
Gender    -> One Hot Encoder <br>
We can directy use Column transformer apply One Hot Encoder and Ordinal Encoder or we apply One Hot Encoder  and Label Encoder separtately

In [7]:
x2=x

In [8]:
ct = ColumnTransformer(transformers=[('Country',OneHotEncoder(),[1]),('Gender',OrdinalEncoder(),[2])],remainder='passthrough')
x= ct.fit_transform(x)
x

array([[1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        1.0000000e+00, 1.0134888e+05],
       [0.0000000e+00, 0.0000000e+00, 1.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 1.1254258e+05],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 1.1393157e+05],
       ...,
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 4.2085580e+04],
       [0.0000000e+00, 1.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 9.2888520e+04],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 3.8190780e+04]])

In [9]:
#using Label Encoder
le = LabelEncoder()
x2.iloc[:,2] = le.fit_transform(x2.iloc[:,2])
ct = ColumnTransformer(transformers=[('Country',OneHotEncoder(),[1])],remainder='passthrough')
x2= ct.fit_transform(x2)
x2

array([[1.0, 0.0, 0.0, ..., 1, 1, 101348.88],
       [0.0, 0.0, 1.0, ..., 0, 1, 112542.58],
       [1.0, 0.0, 0.0, ..., 1, 0, 113931.57],
       ...,
       [1.0, 0.0, 0.0, ..., 0, 1, 42085.58],
       [0.0, 1.0, 0.0, ..., 1, 0, 92888.52],
       [1.0, 0.0, 0.0, ..., 1, 0, 38190.78]], dtype=object)


OrdinalEncoder is for 2D data with the shape (n_samples, n_features)<br>
LabelEncoder is for 1D data with the shape (n_samples,)<br><br>

Oridnal Enoder - The features are converted to ordinal integers,single column of integers (0 to n_categories - 1) per feature.<br>
Label Encoder - Encode target labels with value between 0 and n_classes-1.

In [10]:
# Avoiding Dummy variable Trap
x=x[:,1:]

### Spliting The Datatset

In [11]:
from sklearn.model_selection import train_test_split
x_train, x_test , y_train, y_test = train_test_split(x,y,test_size=0.2,random_state=0)

### Feature Scaling


In [12]:
from sklearn.preprocessing import StandardScaler
sc= StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

### Building Neural Network

In [13]:
import tensorflow as tf

tf.__version__

'2.13.0'

In [14]:
# Initialize the ANN and add Input layer

nn = tf.keras.Sequential()
nn.add(tf.keras.layers.Input(shape=11))

In [15]:
# Adding Hidden Layers
nn.add(tf.keras.layers.Dense(units=7,activation='relu',kernel_initializer='glorot_uniform'))
nn.add(tf.keras.layers.Dense(units=5,activation='relu'))

In [16]:
# Adding Output Layer
nn.add(tf.keras.layers.Dense(units=1,activation='sigmoid'))
nn.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 7)                 84        
                                                                 
 dense_1 (Dense)             (None, 5)                 40        
                                                                 
 dense_2 (Dense)             (None, 1)                 6         
                                                                 
Total params: 130 (520.00 Byte)
Trainable params: 130 (520.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [17]:
# Comiling the Neural Network
nn.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])
nn.layers

In [18]:
# Fitting The model on Training set
nn.fit(x_train,y_train,batch_size=20,epochs=50)

Epoch 1/50
400/400 [==============================] - 3s 3ms/step - loss: 0.5477 - accuracy: 0.7960
Epoch 2/50
400/400 [==============================] - 1s 3ms/step - loss: 0.4602 - accuracy: 0.7960
Epoch 3/50
400/400 [==============================] - 1s 3ms/step - loss: 0.4376 - accuracy: 0.7960
Epoch 4/50
400/400 [==============================] - 1s 3ms/step - loss: 0.4278 - accuracy: 0.7960
Epoch 5/50
400/400 [==============================] - 1s 2ms/step - loss: 0.4223 - accuracy: 0.7985
Epoch 6/50
400/400 [==============================] - 1s 2ms/step - loss: 0.4184 - accuracy: 0.8119
Epoch 7/50
400/400 [==============================] - 1s 2ms/step - loss: 0.4153 - accuracy: 0.8183
Epoch 8/50
400/400 [==============================] - 1s 2ms/step - loss: 0.4124 - accuracy: 0.8220
Epoch 9/50
400/400 [==============================] - 1s 2ms/step - loss: 0.4097 - accuracy: 0.8244
Epoch 10/50
400/400 [==============================] - 1s 3ms/step - loss: 0.4071 - accuracy: 0.8274

### Predictions

In [19]:
y_pred = nn.predict(x_test)
y_pred

63/63 [==============================] - 0s 2ms/step


array([[0.2734216 ],
       [0.29790214],
       [0.11919961],
       ...,
       [0.08184983],
       [0.17980431],
       [0.20416863]], dtype=float32)

In [20]:
y_pred = (y_pred >0.5).astype(np.float32)

In [21]:
from sklearn.metrics import accuracy_score
print(accuracy_score( y_test, y_pred))

0.858


In [22]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,y_pred)
cm

array([[1507,   88],
       [ 196,  209]], dtype=int64)

#### Single Prediction
#### use model to predict the specific person with some details<br>
    Geography: France
    Credit Score: 600
    Gender: Male
    Age: 40 years old
    Tenure: 3 years
    Balance: $60000
    Number of Products: 2
    Does this customer have a credit card ? Yes
    Is this customer an Active Member: Yes 
    Estimated Salary: $50000

In [23]:
'''
France code  is 0,0 after encoding and removing dummy varibale
'''
obs=np.array([0,0,1,700,40,3,0,2,1,1,50000]).reshape(1,11)
obs

array([[    0,     0,     1,   700,    40,     3,     0,     2,     1,
            1, 50000]])

In [24]:
new_pred = nn.predict(sc.transform(obs))
new_pred

1/1 [==============================] - 0s 56ms/step


array([[0.03047127]], dtype=float32)